services:
  qwen3-tts:
    build: .
    container_name: qwen3-tts
    ports:
      - "7860:7860"
    volumes:
      - ./app.py:/app/app.py
      - ./outputs:/app/outputs
      - ./certs:/app/certs
      - qwen3_tts_cache:/root/.cache/huggingface
    environment:
      QWEN_TTS_MODEL: "Qwen/Qwen3-TTS-12Hz-1.7B-Base"
      QWEN_TTS_ATTN: "sdpa"

      QWEN_TTS_SSL_CERT: "/app/certs/qwen.crt"
      QWEN_TTS_SSL_KEY: "/app/certs/qwen.key"

      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    gpus: all

volumes:
  qwen3_tts_cache:
